# Generated by Django 4.1.4 on 2023-02-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_rename_jioningdate_employeedetails_joiningdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='profile',
            field=models.ImageField(blank=True, upload_to='img/'),
        ),
    ]
