# Generated by Django 4.1.4 on 2023-02-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employeedetails_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
