# Generated by Django 4.1.4 on 2023-04-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_employeedetails_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_lec', models.CharField(max_length=200)),
                ('project_name', models.CharField(max_length=200)),
                ('upload', models.FileField(blank=True, null=True, upload_to='img/')),
            ],
        ),
    ]
