# Generated by Django 4.1.4 on 2023-04-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_empachievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empachievement',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
