# Generated by Django 4.1.4 on 2023-04-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_empachievement_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empachievement',
            name='upload',
            field=models.FileField(default='', upload_to='file'),
        ),
    ]
