# Generated by Django 4.1.4 on 2023-04-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_alter_empachievement_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp_Journals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=100)),
                ('upload', models.FileField(default='', null=True, upload_to='file/')),
            ],
        ),
        migrations.CreateModel(
            name='Emp_Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=100)),
                ('upload', models.FileField(default='', null=True, upload_to='file/')),
            ],
        ),
        migrations.AlterField(
            model_name='empachievement',
            name='upload',
            field=models.FileField(default='', null=True, upload_to='file/'),
        ),
    ]
